-- The legacy _default indexes remain available for rollback.
-- Named collection indexes are maintained in scripts/couchbase-layout.mjs.
-- Run npm run db:indexes:couchbase to create and verify them.
